# Generated by Django 3.0.6 on 2020-11-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Symptoms',
            new_name='Symptom',
        ),
    ]
