# Generated by Django 3.0.6 on 2020-12-19 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='dateTime',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
