# Generated by Django 3.0.6 on 2020-12-19 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_record_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='dateTime',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 19, 15, 40, 42, 844899)),
        ),
    ]
