# Generated by Django 3.0.6 on 2021-03-10 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_auto_20201219_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cancer_images')),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='dateTime',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 11, 1, 59, 35, 394125)),
        ),
    ]
